name: Javadoc Generation
on:
  push:
    branches:
    - main
  # pull_request:
  #   branches:
  #   - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java JDK (v21)
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Generate Docs
      run: cd src; javadoc -d docs -noqualifier all -author -use -private sc2002.FCS1.grp2
    - name: Set git commit hash
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload docs as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ steps.vars.outputs.sha_short }}
        path: src/docs/
        compression-level: 6
    - name: Upload static files in preparation for GitHub Pages
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: src/docs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Javadocs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    
        
