name: Javadoc Generation
on:
  push:
    branches:
    - main
    - actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java JDK (v21)
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Generate Docs
      run: cd src; javadoc -d docs sc2002.FCS1.grp2
    - name: Upload docs as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: src/docs/
        compression-level: 5
        
